#!/usr/bin/env bash
# setup.sh — one-shot iOS project materialisation. Run after cloning so the
# generated AcmeBank.xcodeproj is created and opened in Xcode.
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Installing XcodeGen via Homebrew (one-time)…"
  brew install xcodegen
fi

# Write the local Okta/BFF config as an xcconfig that Config/AppConfig.xcconfig
# optionally includes. Xcode bakes these into the built Info.plist via build-
# setting expansion (ProcessInfoPlistFile -expandbuildsettings), so the values
# survive EVERY build — clean or incremental — with nothing to clobber, and the
# build does not depend on Xcode inheriting any environment. Values come from
# the current shell env, else launchctl.
val() { local v="${!1:-}"; [ -n "$v" ] || v="$(launchctl getenv "$1" 2>/dev/null || true)"; printf '%s' "$v"; }
# URLs: `://` -> `:/$()/` so the `//` is not parsed as an xcconfig comment
# (`$()` expands to empty, breaking the comment token, leaving `https://host`).
esc() { printf '%s' "$1" | sed 's#://#:/$()/#g'; }

OKTA_ISSUER_V="$(val OKTA_ISSUER)"
OKTA_CLIENT_ID_V="$(val OKTA_CLIENT_ID)"
OKTA_REDIRECT_URI_V="$(val OKTA_REDIRECT_URI)"
OKTA_SCOPES_V="$(val OKTA_SCOPES)"
API_BASE_URL_V="$(val API_BASE_URL)"
[ -n "$API_BASE_URL_V" ] || API_BASE_URL_V="https://mbdemo-bff-develop.azurewebsites.net"

# Only emit keys that have a value; absent keys fall back to the committed
# __*_UNSET__ sentinels in Config/AppConfig.xcconfig (graceful "not configured").
mkdir -p Config
{
  echo "// Generated by setup.sh — DO NOT COMMIT (gitignored)."
  echo "// URLs use the \`https:/\$()/\` form so \`//\` is not an xcconfig comment."
  # esc() every value: it rewrites `://` -> `:/$()/` and is a verified no-op
  # on values without `//`, so applying it uniformly also protects a redirect
  # URI in the `app://callback` form (whose `//callback` would otherwise be
  # parsed as an xcconfig comment and silently truncated).
  [ -n "$OKTA_ISSUER_V" ]       && echo "OKTA_ISSUER = $(esc "$OKTA_ISSUER_V")"
  [ -n "$OKTA_CLIENT_ID_V" ]    && echo "OKTA_CLIENT_ID = $(esc "$OKTA_CLIENT_ID_V")"
  [ -n "$OKTA_REDIRECT_URI_V" ] && echo "OKTA_REDIRECT_URI = $(esc "$OKTA_REDIRECT_URI_V")"
  [ -n "$OKTA_SCOPES_V" ]       && echo "OKTA_SCOPES = $(esc "$OKTA_SCOPES_V")"
  [ -n "$API_BASE_URL_V" ]      && echo "API_BASE_URL = $(esc "$API_BASE_URL_V")"
} > Config/Secrets.local.xcconfig

if [ -z "$OKTA_ISSUER_V" ]; then
  echo "⚠️  Okta is not configured — OKTA_* env vars are blank."
  echo "    Set them once (see README), e.g.:"
  echo "      launchctl setenv OKTA_ISSUER https://<tenant>.okta.com/oauth2/default"
  echo "    then re-run ./setup.sh."
fi

xcodegen generate

open -a Xcode *.xcodeproj 2>/dev/null || \
  echo "✓ Project generated. Open AcmeBank.xcodeproj in Xcode to start."
